services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh", "-c", "bin/server.sh"]  # Use air for hot reloading
    env_file:
      - .env
    # Enable hot reloading by watching file changes
    restart: unless-stopped